// src/components/sections/OverviewSection.tsx
"use client";

import { Card } from "@tremor/react";
import { formatCurrency, formatPercentage } from "@/lib/utils";
import {
  ArrowUpIcon,
  ArrowDownIcon,
  InfoIcon,
  BarChart3,
  Wallet,
  TrendingUp,
  DollarSign,
  Coins,
  LineChart,
} from "lucide-react";

const MetricCard = ({
  title,
  value,
  change,
  isLoading,
  icon: Icon,
  tooltipText,
}: any) => {
  const isPositive = change > 0;
  const changeColor =
    change === 0
      ? "text-gray-400"
      : isPositive
      ? "text-emerald-400"
      : "text-red-400";

  return (
    <Card className="!bg-gradient-to-b !from-gray-800/70 !to-gray-900/60 border border-gray-700/40 p-5 rounded-2xl shadow-md hover:shadow-lg hover:border-gray-600/60 transition-all duration-300">
      <div className="flex items-start justify-between">
        <div>
          <h3 className="text-sm font-medium text-gray-400 flex items-center">
            {title}
            {tooltipText && (
              <span className="ml-1 cursor-pointer" title={tooltipText}>
                <InfoIcon className="h-4 w-4 text-gray-500" />
              </span>
            )}
          </h3>
          <div className="mt-3">
            {isLoading ? (
              <div className="h-6 bg-gray-700 w-3/4 animate-pulse rounded"></div>
            ) : (
              <p className="text-2xl font-bold text-white mb-1">
                {value !== null ? formatCurrency(value) : "N/A"}
              </p>
            )}
            {change !== null && !isLoading && (
              <div className={`flex items-center text-sm ${changeColor}`}>
                {change === 0 ? null : isPositive ? (
                  <ArrowUpIcon className="h-4 w-4 mr-1" />
                ) : (
                  <ArrowDownIcon className="h-4 w-4 mr-1" />
                )}
                {formatPercentage(change)} 24h
              </div>
            )}
          </div>
        </div>
        {Icon && (
          <div className="p-2 bg-gray-700/50 rounded-xl">
            <Icon className="h-5 w-5 text-gray-300" />
          </div>
        )}
      </div>
    </Card>
  );
};

export default function OverviewSection({ data, isLoading }: any) {
  const protocolData = data || {};

  return (
    <section className="space-y-6">
      <h2 className="text-2xl font-bold text-white mb-2">Protocol Overview</h2>
      <p className="text-sm text-gray-400 mb-4">
        Real-time metrics from Seamless Protocol on Base
      </p>

       <div className="grid grid-cols-2 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
        <MetricCard
          title="Total Value Locked"
          value={protocolData.tvl}
          change={protocolData.tvlChange}
          isLoading={isLoading}
          icon={BarChart3}
          tooltipText="Total capital deposited in the protocol"
        />
        <MetricCard
          title="Total Borrowed"
          value={protocolData.totalBorrow}
          change={null}
          isLoading={isLoading}
          icon={Wallet}
          tooltipText="Total amount borrowed from the protocol"
        />
        <MetricCard
          title="Fees (Annualized)"
          value={protocolData.feesAnnualized}
          change={null}
          isLoading={isLoading}
          icon={TrendingUp}
          tooltipText="Estimated yearly fees generated by the protocol"
        />
        <MetricCard
          title="Revenue (Annualized)"
          value={protocolData.revenueAnnualized}
          change={null}
          isLoading={isLoading}
          icon={DollarSign}
          tooltipText="Estimated yearly revenue for token holders/treasury"
        />
        <MetricCard
          title="SEAM Price"
          value={protocolData.seamPrice}
          change={null}
          isLoading={isLoading}
          icon={Coins}
          tooltipText="Live SEAM token price from DefiLlama"
        />
        <MetricCard
          title="Utilization"
          value={protocolData.utilization}
          change={null}
          isLoading={isLoading}
          icon={LineChart}
          tooltipText="Percentage of total supply currently borrowed"
        />
      </div>
    </section>
  );
}
